from __future__ import annotations

SWING_LOOKBACK: int = 5
FVG_ATR_MULTIPLIER: float = 0.1
LIQUIDITY_TOLERANCE: float = 0.001  # 0.1%
LIQUIDITY_MIN_COUNT: int = 2
BPR_MAX_AGE_CANDLES: int = 100
BPR_MIN_OVERLAP_RATIO: float = 0.3
ATR_PERIOD: int = 14
PO3_ACCUM_LOOKBACK: int = 6
PO3_ACCUM_ATR_THRESH: float = 0.5
PO3_MANIP_WINDOW: int = 6
PO3_DISTRIB_WINDOW: int = 12
PO3_DISTRIB_ATR_MIN: float = 0.8
